version: '3.5'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: perspective-test
    container_name: perspective-db
    ports:
      - '5432:5432'

  api:
    build:
      context: .
      dockerfile: ./apps/services/Dockerfile
    container_name: perspective-api
    ports:
      - '8080:8080'
    depends_on:
      - postgres